[package]
name = "cqrusty"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.140"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-async-std", "time"] }
